apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: HF-ITCNE24-SemArbeit3-MSVC-Lizenztool
  description: License Tool
  tags:
    - lizenzen
    - flask
    - python
    - blueprints
    - mg-graph
spec:
  type: service
  lifecycle: experimental
  owner: miguel